repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c, .yamllint]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: ^tests/

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^tests/
        args: [--max-line-length=120, --extend-ignore=E203]

  - repo: local
    hooks:
      - id: local-test-suite
        name: run local python unit tests
        entry: python3 -m unittest discover -s tests
        language: system
        pass_filenames: false
        always_run: true
